cv:
    resource: "@CvBundle/Resources/config/routing.yml"
    prefix:   /cv

todo_list:
    resource: "@TodoListBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
